apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-static
  namespace: pbs-taiga
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-media
  namespace: pbs-taiga
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
