apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-back
  namespace: pbs-taiga
  labels:
    app: taiga-back
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: taiga-back
  template:
    metadata:
      labels:
        app: taiga-back
    spec:
      nodeSelector:
        kaas.infomaniak.cloud/instance-pool: pck-8kxhclv-pdp
      volumes:
        - name: taiga-static
          persistentVolumeClaim:
            claimName: taiga-static
        - name: taiga-media
          persistentVolumeClaim:
            claimName: taiga-media
      containers:
        - name: taiga-back
          image: ghcr.io/scout-ch/pbs-taiga-back:latest@sha256:c3550706366cd68c5c89746c5ec1f56524c62981c8ed17a48e8bfc42890cd36e
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: taiga-config
            - secretRef:
                name: taiga-secrets
          volumeMounts:
            - name: taiga-static
              mountPath: /taiga-back/static
            - name: taiga-media
              mountPath: /taiga-back/media
          readinessProbe:
            httpGet:
              path: /api/v1/
              port: 8000
          startupProbe:
            httpGet:
              path: /api/v1/
              port: 8000
            periodSeconds: 1
            failureThreshold: 60
          livenessProbe:
            httpGet:
              path: /api/v1/
              port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: taiga-back
  namespace: pbs-taiga
spec:
  selector:
    app: taiga-back
  ports:
    - port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taiga-back
  namespace: pbs-taiga
  labels:
    app: taiga-back
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  rules:
    - host: taiga.scout.ch
      http:
        paths:
          - pathType: Prefix
            path: "/admin"
            backend:
              service:
                name: taiga-back
                port:
                  number: 8000
          - pathType: Prefix
            path: "/api"
            backend:
              service:
                name: taiga-back
                port:
                  number: 8000
